### PR TITLE
Fix self-atari error in mcplayout()

### PR DESCRIPTION
**Pull request by traveller42**
Test was claiming self-atari when that was not the case.

### CODE REVIEW

**Comment by traveller42** [comment]
I found this when investigating why my Golang version and the Python version were playing out `mcdebug` differently after I had removed all the random elements.

**Comment by pasky** [comment]
So, what this does in effect is allowing to pull out edge group that's capturable in a ladder. But is that a good idea?

**Comment by traveller42** [comment]
So while not immediate self-atari, it can be force-captured.  Correct?

**Comment by pasky** [comment]
That's right.

**Comment by traveller42** [comment]
I have a version of the engine with and without the suggested fix.

Let me run them for a few days against each other and see what we get.

**Comment by traveller42** [comment]
Still testing.

It's going a bit slow as my primary computer has a hardware failure.

First run of 20 came up 10/10 between the `master` branch and the `self_atari` branch.  I also matched the differences on the Golang side and that pair was 13/7 between each other.

Looking at how they played in the pool, there was a slight advantage (not significant due to the small number of games) to proposed code.

I will run more tests and include a few other programs to see if there is a significant difference in the results.

**Comment by traveller42** [comment]
Further testing does not show a significant advantage to this proposal.  There is the slightest advantage (a game or 2 out of 100) to the existing code.

I will be incorporating the existing test in my code as well.

**Comment by pasky** [comment]
Thanks for testing!

**Pull request closed without merging**
